# Generated by Django 5.1.2 on 2024-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Portfolio Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills'),
        ),
    ]
